server:
  port: 9002   
spring:
  datasource:
    url: jdbc:postgresql://order-service.xyz:5432/order-service
    username: 
    password: 
    initialization-mode: always
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
   
 
     
