server:
  port: 9002   
spring:
  datasource:
    url: jdbc:postgresql://order-service.c0gyt9kjte0h.us-east-1.rds.amazonaws.com:5432/order-service
    username: root
    password: eclipse123
    initialization-mode: always
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
   
 
     